### ISSUE TITLE
Wrap citation format in a try{}catch{} block

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#183]
**Describe the bug**
One bad citation will kill an entire page

**To Reproduce**

[Howitt](http://localhost/person/1669b06de2610b1526fff828b1d1c5b2)
[Eisen](http://localhost/person/226d2dccfba4c2be04aedd4f9f942e42)

**Expected behavior**
We need to place every citation in a try{} catch{} function, and just skip bad errors. However, if we do this, we need a convenient way to count the number of errors for a person so that we can follow up on this.  This can be both a flag to the page eg `?show_errors` and some way to get the count via json if possible.

**Comment by UcDust** [comment]
@qjhart 

It looks like a couple of [Howard's citations](localhost/person/1669b06de2610b1526fff828b1d1c5b2) are an array of dates instead of a date-

<img width="524" alt="Screenshot 2023-09-29 at 11 06 31" src="https://github.com/ucd-library/aggie-experts/assets/103536473/cf5942f5-1e00-454b-a4fa-605d21dac888">

In that situation, should we use the first or second date, or both somehow?
