### ISSUE TITLE
Missing grant info

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/aggie-experts#274]
**Describe the bug**
Some of our grants in Elements do not show data about dates or funder, even though most do. What is different about them?

**To Reproduce**
These are the grants that are in Elements only as Titles, associated with investigators. How do they appear in our feed to Elements? Do they have other data elements?
ark:/87287/d7gt0q/grant/119843
ark:/87287/d7gt0q/grant/114244
ark:/87287/d7gt0q/grant/127601
ark:/87287/d7gt0q/grant/116828
ark:/87287/d7gt0q/grant/110381

**Comment by rakunkel-ucd** [comment]
I don't find these IDs in our feed file. These examples where uploaded to QA on our first import attempt (9/27). Since then we have narrowed our selection and these grants were excluded. We also fixed our import file so that the complete records are mapped. We have no way to delete these or we would do that. They will be deleted when CDL does a data refresh from prod to QA.

**Comment by Vensberg** [comment]
Great!
