### ISSUE TITLE
Add an MIV service account and information on getting a token

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#338]
We are updating our authorization method for all library applications. We
are using a single keycloak authorization server, and using that to mint
signed tokens, define roles and manage active tokens.

## Proposal
For MIV, we’ll share an miv user/password service account combination, that
does not require full CAS identification. We’ll also specify an MIV
client with a client secret. The MIV team can use this to generate an authorization
token for accessing aggie-experts. 

We are looking into making this specific token long lived, even though you can get them on demand, like per-request.

**Comment by qjhart** [comment]
http://sandbox.auth.library.ucdavis.edu has a proposed methodology for the above implementation.  First, we've created a new client for aggie experts `miv` which only allows direct access token generation: 

## Keycloak Client 

![image](https://github.com/ucd-library/glm-lightning/assets/344953/acbd1e85-2cb7-4764-85cb-f2f8808ae283)

This client will *only* be used with MIV and *only* with the MIV service account.  The service account will have the role `miv`.  This is a realm role, and if we want to attach it to regular users for testing, we can do that in the other clients.

## Service
Now, the MIV  team can use this client (where we share the client_secret) and their `miv` user token to fetch a token.  For example

```bash
http --form https://sandbox.auth.library.ucdavis.edu/realms/aggie-experts/protocol/openid-connect/token grant_type=password username=miv password=${miv_password} scope='roles openid profile email' client_id=miv client_secret=${client_secret} | tee miv_access_token.json
```

Now we can access aggie-experts with this elevated authorization, for example this query shows we are getting unsanitized data. (is-visible: false)

```bash
http http://localhost/api/expert/expert/66356b7eec24c51f01e757af2b27ebb8?no-sanitize Authorization:"Bearer $(jq -r .access_token miv_access_token.json)" | jq . | grep is-visible | sort -u
        "is-visible": false
        "is-visible": true
        "is-visible": true,
      "is-visible": true,
```

I've also verified that we can remove the sessions, and the token no longer can be used.

**Comment by qjhart** [comment]
One problem I am finding is that I can't seem to get the client specific session overrides to work.  If, for example, we want to give these tokens a *very* long ttl, I can't seem to make that work.  For example with the values below, I still only get 1 day expirations for this clients token.

![image](https://github.com/ucd-library/glm-lightning/assets/344953/17bcf089-9c01-4b18-bdbe-63f9953d78c0)

**Comment by rakunkel-ucd** [comment]
I am not able to fetch a token using the gc secret manager miv-service-account-credentials secret for miv_password and the keycloak client secret for client_secret

**Comment by rakunkel-ucd** [comment]
Here are the steps to follow to access a secret from GCS Secret Manager:
1. Install Google Cloud SDK: The Google Cloud SDK includes the gcloud command-line tool, which is necessary to interact with GCS Secret Manager. You can install it by following the instructions on the [Google Cloud SDK Documentation](https://cloud.google.com/sdk/docs/install).
2. Authenticate with Google Cloud: After installing the SDK, You need to authenticate with Google Cloud. You can do this by running the following command in your terminal:
gcloud auth login
This command will open a new browser window where you can log in with your Google account. After logging in, you can close the browser window and return to the terminal.
3. Access the Secret: Once you are authenticated, you can access the secret using the gcloud secrets versions access command. In our script, this command is used to store the secret in the cred variable. You can run a similar command in your terminal, replacing ${secret} with the name of the secret you want to access:
gcloud secrets versions access ${secret}
This command will print the secret to the terminal. If you want to store the secret in a variable like in our script, you can use command substitution:
cred=$(gcloud secrets versions access ${secret})

**Comment by rakunkel-ucd** [comment]
Here is a bash script that demonstrates the process of retrieving the miv crendentials from GCS, using them to retrieve a JWT token from our Keycloak auth server, and calling the grants endpoint with parameters.

#!/bin/bash
host=https://stage.experts.library.ucdavis.edu/
get_token=${host}/auth/keycloak-oidc/service-account/token
get_grants=${host}/api/miv/grants
secret=projects/325574696734/secrets/miv-service-account-credentials/versions/2
cred=$(gcloud secrets versions access ${secret})
token=$(http ${get_token} Content-type:application/json <<< "${cred}" | jq -r .access_token)
uuid=$1  # Accept uuid as a command-line argument
since=$2 # Accept since as a command-line argument
until=$3 # Accept until as a command-line argument
http_command="http ${get_grants} ucdPersonUUID==${uuid} "
if [ -n "$since" ]; then
    http_command+=" since==${since}"
fi
if [ -n "$until" ]; then
    http_command+=" until==${until}"
fi
http_command+=" Authorization:\"Bearer ${token}\""
eval $http_command





[10:39](https://ucdavis.slack.com/archives/C03RDBNR6TA/p1714498768467549)
Usage example:  ./keycloak-token.sh 00021386 2008-01-01 2013-01-01





[10:41](https://ucdavis.slack.com/archives/C03RDBNR6TA/p1714498890236689)
Of course, you don't have to use this script, but it shows the under necessary components.
