### ISSUE TITLE
My Account dropdown stays open when it should close

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/aggie-experts#419]
The "My Account" dropdown currently stays open unless you click "My Account" again. This is **not expected nor desired** behavior.

The dropdown should **close** if you do any of the following:
- click on an option in the dropdown
- navigate to a different page
- click anywhere outside of the dropdown

Video example of bug (Mac OS, Chrome):

https://github.com/ucd-library/aggie-experts/assets/17831969/ca697f73-8296-4e1d-ab81-382f06c6da53

**Comment by UcDust** [comment]
The same behavior exists for the search dropdown, and header navigation 'clicks' in mobile view. I can address that in this issue as well.

The problem is the component doesn't close by default in SPAs; since page navigation doesn't trigger a new network request, the element remains in the previous state.
