### ISSUE TITLE
Expert availability ui and api updates

### ISSUE THREAD

**Issue by UcDust** [ucd-library/aggie-experts#529]
Experts should have the ability to indicate projects and community availability, as in:

![Image](https://github.com/ucd-library/aggie-experts/assets/103536473/f59e89c2-ce5b-49a7-b1d1-a753d324ac2c)

Determine where the data will persist in fcrepo/elastic.

Also the search page needs to be extended to filter by the various _open to_ preferences.

- [x] Update the expert profile page with labels and modal to make changes in edit mode
- [x] Update the search page to have filters for availability
- [ ] Update the search api code to filter results by availability
- [ ] Update the expert api code to save edits to CDL

**Comment by UcDust** [comment]
@Vensberg 
I was just chatting with @wrenaria regarding the ui for the open-to/availability feature we're adding to AE. Are each of these preferences opt-in, so that by default nothing is enabled/checked?

**Comment by Vensberg** [comment]
@UcDust , they will be fed by Availability label data in Elements. It's new data.

**Comment by qjhart** [comment]
In terms of updates, there is existing generic user profile update code at [userprofile](https://github.com/ucd-library/aggie-experts/blob/49d21d6274081fb8eca4ba91d4cecbb0b119698f/experts-api/lib/elements-client.js#L315) This is used for example at [updateUserPriviacyLevel](https://github.com/ucd-library/aggie-experts/blob/49d21d6274081fb8eca4ba91d4cecbb0b119698f/experts-api/lib/elements-client.js#L358).  We need to see if updates to the availability follow this pattern, of if they have their own endpoint.

**Comment by qjhart** [comment]
@Vensberg looking at production it appears like we ended up creating a new Availability label scheme.  I thought we were going to use a subset of the existing availability labels.  Was that incorrect? 

If we are adding a new one, we should probably think about one set of labels for *all* aggie experts parts.  I kinda like using the baked in one better for this.

**Comment by Vensberg** [comment]
We needed to add community partnerships. We have a stakeholder request for that.

**Comment by qjhart** [comment]
@UcDust, OK @Vensberg has let me know we aren't interested in collaborating with CDL about a common availability controlled vocabulary, and we are going to use a ucd specific one.  So, I've updated `fcrepo-dev` to include these.  I have added our own `hasAvailability` flag, so a user looks like: 

``` json
"@graph": [
{
"@id": "expert/LDdgBTXN",
...,
"hasAvailability": [
{
"@id": "ark:/87287/d7nh2m/keyword/c-ucd-avail/Join%20a%20web%20conference%20as%20a%20panellist%20or%20speaker",
"@type": "Concept",
"availabilityOf": "expert/LDdgBTXN",
"inScheme": "ark:/87287/d7nh2m/keyword/c-ucd-avail/",
"prefLabel": "Join a web conference as a panellist or speaker"
},
{
"@id": "ark:/87287/d7nh2m/keyword/c-ucd-avail/Teaching%20provision",
"@type": "Concept",
"availabilityOf": "expert/LDdgBTXN",
"inScheme": "ark:/87287/d7nh2m/keyword/c-ucd-avail/",
"prefLabel": "Teaching provision"
},
{
"@id": "ark:/87287/d7nh2m/keyword/c-ucd-avail/Community-engaged%20projects",
"@type": "Concept",
"availabilityOf": "expert/LDdgBTXN",
"inScheme": "ark:/87287/d7nh2m/keyword/c-ucd-avail/",
"prefLabel": "Community-engaged projects"
},
{
"@id": "ark:/87287/d7nh2m/keyword/c-ucd-avail/Collaborative%20projects",
"@type": "Concept",
"availabilityOf": "expert/LDdgBTXN",
"inScheme": "ark:/87287/d7nh2m/keyword/c-ucd-avail/",
"prefLabel": "Collaborative projects"
},
```

For display, only include the ones that have 

```json
"inScheme": "ark:/87287/d7nh2m/keyword/c-ucd-avail/",
```

**Comment by qjhart** [comment]
@UcDust Need to be in the `qh-availability` branch for this to display properly

**Comment by UcDust** [comment]
@qjhart @Vensberg 

It looks like the list of availabilities in the api response are these:

```
"Join a web conference as a panellist or speaker"
"Teaching provision"
"Community-engaged projects"
"Collaborative projects"
"Media enquiries"
"Mentoring (long-term)"
"Career advice"
"Technical support"
"Masters Research or PhD student supervision"
"Mentoring (short-term)"
"Membership of an advisory committee"
"Industry Projects"
```

Does that look right? Also, is it likely that this data could change over time?

**Comment by Vensberg** [comment]
I changed "Community-engaged projects" to "Community partnerships" to be identical with the Aggie Experts wording. 

We will be using only four of these Elements labels in Aggie Experts:
| Elements label | Aggie Experts label |
| --- | --- |
| "Community partnerships" | Community Partnerships |
| "Collaborative projects" | Collaborative Projects |
| "Media enquiries" | Media Interviews |
| "Industry Projects" | Industry Projects |

**Comment by wrenaria** [comment]
@Vensberg:
> I changed "Community-engaged projects" to "Community partnerships" to be identical with the Aggie Experts wording.

Related to this, would you like to change "media interviews" to "media enquiries" in Aggie Experts so that we match the Elements label? Enquiries and interviews seem like equally fine words, so the consistency might be nice.

@UcDust:
Since it's preferred that users make all desired availability selections prior to saving, the design has been changed to a modal solution. Tooltip hover on the Edit button should say "Edit availability."

In Figma, these pages are updated to reflect the change:
- [Profile User Admin](https://www.figma.com/design/VFlaWRDVaiF1lOeQu9NEW4/Aggie-Experts?node-id=896-6697)
- [Experts "Open to" Feature](https://www.figma.com/design/VFlaWRDVaiF1lOeQu9NEW4/Aggie-Experts?node-id=2689-7686)

Screenshots from Figma:
Display | Profile View | Editing Modal |
| --- | --- | --- |
Desktop | ![Screenshot 2024-06-20 at 2 15 18 PM](https://github.com/ucd-library/aggie-experts/assets/17831969/49808293-bc09-4046-8ceb-3c29a4f40e55) | ![Screenshot 2024-06-20 at 2 15 45 PM](https://github.com/ucd-library/aggie-experts/assets/17831969/15fa1e4a-1563-42e2-a92b-e34692f306d1)
Mobile | ![Screenshot 2024-06-20 at 2 14 28 PM](https://github.com/ucd-library/aggie-experts/assets/17831969/c45394b9-6b70-4eb2-895f-6e668231bc0a) | ![Screenshot 2024-06-20 at 2 14 37 PM](https://github.com/ucd-library/aggie-experts/assets/17831969/5a126924-58cd-443e-abe8-b55b167cba46)

**Comment by UcDust** [comment]
@Vensberg 

When updating the availability labels, it's possible (hopefully not likely) that the update to CDL could fail. 

If that happens, should we show a warning modal like we have a in a few other places? Would verbiage like this work for you?:

```
Updating expert availability labels could not be done through Aggie Experts right now. Please, try again later, or make changes directly in the <a href="https://oapolicy.universityofcalifornia.edu/">UC Publication Management System.
```

**Comment by Vensberg** [comment]
That works, but can it redirect the user to to the editing interface of the Elements user profile in a new tab?

**Comment by wrenaria** [comment]
@Vensberg Accessibility best practices is that links always open in the same window when possible to avoid loss of context. If you want links to open in a new tab, it needs to be explicitly stated that the link will open in a tab in order to avoid confusion. This is especially important for vision impaired users.

If users want to use a new tab, they can make that decision manually (right-click, open in new tab or window).

**Comment by Vensberg** [comment]
@wrenaria , I meant for it to work similarly to the Introduction and Links editing workflow, where the pop-up window that explains the process shows up on the same page, but the edit button from there opens Elements in a new tab.

**Comment by wrenaria** [comment]
@Vensberg The fact that it is already being done elsewhere doesn't change the reality that opening links in a new tab without warning is an accessibility problem; it means we need to adjust either the link text or behavior across the whole site. I missed that this link behavior was happening, or I would have said something earlier.

https://www.w3.org/TR/WCAG20-TECHS/G200.html

Best practice is to not open links in a new tab. Second best is to warn them using text associated with the link itself. Minimum compliance would be to include the warning in the modal text prior to the yellow "edit" button that appears on most modals -- for example, change `You will be redirected to this system` to `You will be redirected to this system in a new tab`.

**Comment by Vensberg** [comment]
@wrenaria , I like the second option: "You will be redirected to this system in a new tab"

**Comment by wrenaria** [comment]
@Vensberg I've created a new issue for this topic, please sign off on my proposed solution there -- issue #543

**Comment by Vensberg** [comment]
@UcDust , Elements has been updated with the shortened version of UCD labels.
