### ISSUE TITLE
[FEAT] Search Aggregations

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#643]
Search results need aggregations on :+1: 

type:
status

**Comment by UcDust** [comment]
We'll have filters on the search page similar to this:

![image](https://github.com/user-attachments/assets/38715b15-5687-4755-85b3-96183cc0098e)

Results for _Grants_ and _Experts_ will show up when they're selected, of course. When _Experts_ or _All Results_ are selected, the _Experts Open To_ section will show up, and allow filtering of experts for the current search term to those with specific availabilities.

The availability filters shouldn't affect the grants that are returned for the search, so the number of experts will be the only thing that changes. Using the screenshot above as reference, if they have an availability filter selected so that only 9 experts are returned, when _All Results_ is selected, the 9 experts + the 39 grants should show up in the search results.

**Comment by qjhart** [comment]
@UcDust I have added another endpoint to the search:

```bash
http http://localhost/api/search/types q==hart Authorization:"Bearer $jwt"
```
results in :
```json
{
    "aggregations": {
        "type": {
            "expert": 1,
            "grant": 7,
            "grant_research": 7
        }
    },
    "total": 8
}
```

```bash
http http://localhost/api/search/types Authorization:"Bearer $jwt"
```
results in :
```json
{
    "aggregations": {
        "type": {
            "expert": 4,
            "grant": 91,
            "grant_research": 90,
            "grant_service": 83
        }
    },
    "total": 95
}
```

So the question for you is should we run this on every search query and update the aggregations, or do you want to manage in the client?   You can comment and assign back to me.

**Comment by qjhart** [comment]
@UcDust, that wasn't clear :).  I still don't understand how you're expecting this to work, so I have two proposals;

##  Two Aggregations 

We could return two aggregations, one on the query only, and one on the complete query.    This would allow you to limit your experts to those wanting media, but still open grants, and see how many are active, etc.

Something like: 

```bash
http http://localhost/api/search type==grant status==active Authorization:"Bearer $jwt"  | jq .aggregations
```
```json
{
  "query_only": {
    "availability": {
      "ark:/87287/d7mh2m/keyword/c-ucd-avail/collaborative%20projects": 2,
      "ark:/87287/d7mh2m/keyword/c-ucd-avail/community%20partnerships": 1,
      "ark:/87287/d7mh2m/keyword/c-ucd-avail/industry%20projects": 1,
      "ark:/87287/d7mh2m/keyword/c-ucd-avail/media%20enquiries": 1
    },
    "type": {
      "grant": 91,
      "grant_research": 90,
      "grant_service": 83,
      "expert": 4
    },
    "status": {
      "completed": 86,
      "active": 5
    }
  },
  "complete": {
    "availability": {},
    "type": {
      "grant": 5,
      "grant_research": 5,
      "grant_service": 4
    },
    "status": {
      "active": 5
    }
  }
}
```

**Comment by qjhart** [comment]
@UcDust I've updated using the first example, let me know if you agree
